json_structure={"id":{
    "132456789":{
        "name":"name",
        "email":"email",
        "phone":"phone",
        "Company":"company",
        "website":"website",
        "category":"category",
        "description":"description",
        "Comp_scale":"comp_scale",
        "products":{
            "product1":{
                "name":"product1",
                "price":"price1",
                "category":"category1",
                "description":"description1"
            },
            "product2":{
                "name":"product2",
                "price":"price2",
                "category":"category2",
                "description":"description2"
            }
        }
    }
}
}